#!/usr/bin/env node
/**
 * Example: Research Agent Script Runtime
 *
 * This script is designed to run inside a vibly script runtime.
 * It reads the work order from the VIBLY_WORK_ORDER_JSON environment variable,
 * performs research (stubbed here), and writes result.json + report.md to
 * the VIBLY_OUTPUT_DIR directory.
 *
 * Usage (register this script as a runtime):
 *   vibly runtime register-script --name research-agent --command "node examples/runtimes/research-agent.js"
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const workOrderJson = process.env.VIBLY_WORK_ORDER_JSON;
const outputDir = process.env.VIBLY_OUTPUT_DIR ?? "/tmp/vibly-output";

if (!workOrderJson) {
  console.error("VIBLY_WORK_ORDER_JSON is not set");
  process.exit(1);
}

const workOrder = JSON.parse(workOrderJson);

mkdirSync(outputDir, { recursive: true });

// --- Stub: replace with real research logic ---
const title = workOrder.title ?? workOrder.id ?? "Unknown Task";
const summary = `Research completed for: ${title}. This is a stub result — replace with real logic.`;

const report = `# Research Report

**Work Order**: ${workOrder.id ?? "unknown"}
**Title**: ${title}
**Completed At**: ${new Date().toISOString()}

## Summary

${summary}

## Findings

- Finding 1: Stub data (replace with actual research results)
- Finding 2: Stub data
- Finding 3: Stub data

## Conclusion

This report was generated by the example research-agent script runtime.
`;

writeFileSync(join(outputDir, "report.md"), report);
writeFileSync(
  join(outputDir, "result.json"),
  JSON.stringify({ summary, confidence: 0.85, artifacts: ["report.md"] }, null, 2),
);

console.log(JSON.stringify({ summary }));
